project:
  type: website
  output-dir: _site
  render:
  - "*.qmd"
  - "!*.md"
execute:
  freeze: auto
author:
  - name: A. Student
    email: astudent@allegheny.edu
website:
  title: "Junior Seminar Research Journal"
  navbar:
    right:
      - text: "Junior Seminar Research Report"
        href: report/index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: journal
    css: styles.css
